[package]
name = "rusty_rover"
version = "0.1.0"
authors = ["Adam Trilling <adamtrilling@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
